// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_Web'].toString(),
    appId: '1:792254931416:web:0614d32afdd14e2c9512ad',
    messagingSenderId: '792254931416',
    projectId: 'chat-app-1eb2b',
    authDomain: 'chat-app-1eb2b.firebaseapp.com',
    storageBucket: 'chat-app-1eb2b.appspot.com',
    measurementId: 'G-9F6H7HL3YE',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_Android'].toString(),
    appId: '1:792254931416:android:3109fe8b2c23779d9512ad',
    messagingSenderId: '792254931416',
    projectId: 'chat-app-1eb2b',
    storageBucket: 'chat-app-1eb2b.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_IOS'].toString(),
    appId: '1:792254931416:ios:3d0468fd721b9c2a9512ad',
    messagingSenderId: '792254931416',
    projectId: 'chat-app-1eb2b',
    storageBucket: 'chat-app-1eb2b.appspot.com',
    iosClientId: '792254931416-phefpe706uisgo4ladle9o5t7p0fpda8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_Macos'].toString(),
    appId: '1:792254931416:ios:fb5cd925f74d7c199512ad',
    messagingSenderId: '792254931416',
    projectId: 'chat-app-1eb2b',
    storageBucket: 'chat-app-1eb2b.appspot.com',
    iosClientId: '792254931416-39ho7lmrqmshp4dbifc94tkqljehaj33.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
